defaultSemverRangePrefix: ''

enableGlobalCache: true

nmMode: hardlinks-global

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'
  - checksum: 014b1ae3007ca2fd397417e73afe2af9e6451ffe8defdbfbcdab0b89c0803bfbff586bfc63ef59524d901e234b981686d3cd01b055590cf208533408e8f36f5d
    path: .yarn/plugins/plugin-auto-install.cjs
    spec: 'https://github.com/WillBooster/yarn-plugin-auto-install/releases/download/v1.8.5/index.min.cjs'

yarnPath: .yarn/releases/yarn-4.0.0-rc.34.cjs
