export const Extensions = {
  codeWith2IndentSize: [
    'cpp',
    'dart',
    'htm',
    'html',
    'js',
    'json',
    'jsx',
    'pu',
    'puml',
    'rb',
    'ts',
    'tsx',
    'vue',
    'yaml',
    'yml',
  ],
  codeWith4IndentSize: ['go', 'gradle'],
  markdownLike: ['md'],
  eslint: ['js', 'jsx', 'ts', 'tsx'],
  prettier: ['css', 'htm', 'html', 'js', 'json', 'jsx', 'md', 'scss', 'ts', 'tsx', 'vue', 'yaml', 'yml'],
};
