export const Extensions = {
  codeWith2IndentSize: [
    'cpp',
    'dart',
    'htm',
    'html',
    'js',
    'json',
    'jsx',
    'pu',
    'puml',
    'rb',
    'ts',
    'tsx',
    'vue',
    'yaml',
    'yml',
  ].sort(),
  codeWith4IndentSize: ['go', 'gradle', 'py'].sort(),
  codeWith8IndentSize: ['sh'].sort(),
  markdownLike: ['md'].sort(),
  eslint: ['js', 'jsx', 'ts', 'tsx'].sort(),
  prettier: ['css', 'htm', 'html', 'js', 'json', 'jsx', 'md', 'scss', 'ts', 'tsx', 'vue', 'yaml', 'yml'].sort(),
};
