export const extensions = {
  codeWith2IndentSize: [
    'cjs',
    'mjs',
    'js',
    'jsx',
    'cts',
    'mts',
    'ts',
    'tsx',
    'json',
    'json5',
    'jsonc',
    'cpp',
    'dart',
    'htm',
    'html',
    'pu',
    'puml',
    'rb',
    'vue',
    'xml',
    'yaml',
    'yml',
    'sh',
  ].toSorted(),
  codeWith4IndentSize: ['go', 'gradle', 'java', 'py'].toSorted(),
  markdownLike: ['md'].toSorted(),
  eslint: ['cjs', 'mjs', 'js', 'cts', 'mts', 'ts', 'tsx', 'jsx'].toSorted(),
  prettier: [
    'cjs',
    'mjs',
    'java',
    'js',
    'jsx',
    'cts',
    'mts',
    'ts',
    'tsx',
    'json',
    'json5',
    'jsonc',
    'css',
    'htm',
    'html',
    'md',
    'scss',
    'vue',
    'yaml',
    'yml',
  ].toSorted(),
  // cf. https://biomejs.dev/internals/language-support/
  biome: [
    'cjs',
    'mjs',
    'js',
    'jsx',
    'cts',
    'mts',
    'ts',
    'tsx',
    'json',
    'json5',
    'jsonc',
    'htm',
    'html',
    'vue',
    'svelte',
    'astro',
    'css',
    'yaml',
    'yml',
    'gql',
  ].toSorted(),
};
