import { test, expect } from 'vitest';

import { ignoreFileUtil } from '../src/utils/ignoreFileUtil';

test.each([
  {
    content: 'aaa',
    headContent: ignoreFileUtil.defaultHeadUserContent,
    tailContent: ignoreFileUtil.defaultTailUserContent,
  },
  {
    content: `# Project-specific settings
1
# Generated by wbfy
2
# Project-specific settings (tail)
3`,
    headContent: `# Project-specific settings (head)
1
# Generated by wbfy
`,
    tailContent: `
# Project-specific settings (tail)
3`,
  },
])('get user contents', ({ content, headContent, tailContent }) => {
  expect(ignoreFileUtil.getHeadUserContent(content)).toEqual(headContent);
  expect(ignoreFileUtil.getTailUserContent(content)).toEqual(tailContent);
});
