name: Generate PR with Gemini CLI
on:
  issues:
    types:
      - labeled
  pull_request:
    types:
      - labeled
jobs:
  gen-pr:
    if: contains(github.event.label.name, 'gen-pr-all') || contains(github.event.label.name, 'gen-pr-gemini')
    uses: WillBooster/reusable-workflows/.github/workflows/gen-pr.yml@main
    with:
      coding-tool: gemini-cli
      issue-number: ${{ github.event.issue.number || github.event.number }}
    secrets:
      GEMINI_CLI_OAUTH_TOKEN: ${{ secrets.GEMINI_CLI_OAUTH_TOKEN }}
      GH_TOKEN: ${{ secrets.PUBLIC_GH_BOT_PAT }}
