name: Test

on:
  pull_request:
    branches:
      - 'main'
      - '!renovate/**'
  push:
    branches:
      - 'main'
      - 'renovate/**'

jobs:
  test:
    uses: WillBooster/reusable-workflows/.github/workflows/test.yml@main
    with:
      dot_env_path: .env
      non_self_hosted: true
    secrets:
      DOT_ENV: 'FIREBASE_PROJECT_ID=test'
