name: Willboosterify
on:
  schedule:
    - cron: 0 5 * * 0
  workflow_dispatch:
jobs:
  wbfy:
    uses: WillBooster/reusable-workflows/.github/workflows/wbfy.yml@main
    with:
      non_self_hosted: true
